/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/scene.gltf -t
Author: waimus (https://sketchfab.com/waimus)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/world-cup-trophy-c4ae2dd470194a81b856ad84620d8beb
Title: World Cup Trophy
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    wctrophy_globe_low_globe_0: THREE.Mesh;
    wctrophy_body_low_body_0: THREE.Mesh;
  };
  materials: {
    globe: THREE.MeshStandardMaterial;
    body: THREE.MeshStandardMaterial;
  };
};

export function GoldCupModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.wctrophy_globe_low_globe_0.geometry}
        material={materials.globe}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.wctrophy_body_low_body_0.geometry}
        material={materials.body}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
